[project]
name = "new_p"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "Flask>=3.1.1",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []